include: package:pedantic/analysis_options.yaml

linter:
  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false
    prefer_const_constructors: false
    prefer_initializing_formals: false